package dummy

var DummyTemplateFields = []map[string]interface{}{
	//Example 1 template fields
	{
		"id":                   "1c2c54b5-e76f-4dbf-9e60-d814b0ac7ab2",
		"field_name":           "Example Field",
		"is_dynamic":           true,
		"field_type":           "number",
		"suffix":               "usdc",
		"field_length":         "full",
		"placeholder":          "Enter a number",
		"is_required":          true,
		"is_tooltip":           true,
		"tooltip_text":         "Example tooltip",
		"metadata_id":          "b0e1c1d5-d078-4856-80e3-416aa438520a",
		"position_in_metadata": 0,
	},
	{
		"id":                   "dde00b4c-bf9c-45b6-911d-e23ddcbe2f35",
		"field_name":           "Example file field",
		"is_dynamic":           false,
		"field_type":           "file",
		"suffix":               nil,
		"field_length":         "full",
		"placeholder":          nil,
		"is_required":          false,
		"is_tooltip":           true,
		"tooltip_text":         "Example tooltip",
		"metadata_id":          "b0e1c1d5-d078-4856-80e3-416aa438520a",
		"position_in_metadata": 0,
	},
	// Example 2 template fields
	{
		"id":                   "467ce192-75c4-466e-8800-d22076dd8f44",
		"field_name":           "Name",
		"is_dynamic":           false,
		"field_type":           "string",
		"suffix":               nil,
		"field_length":         "full",
		"placeholder":          "Type a name",
		"is_required":          false,
		"is_tooltip":           false,
		"tooltip_text":         nil,
		"metadata_id":          "a655f2a2-cd06-470e-8512-071a717d7e09",
		"position_in_metadata": 0,
	},
	{
		"id":                   "f117bc9a-3c36-4912-be34-7484550242a7",
		"field_name":           "Surname",
		"is_dynamic":           false,
		"field_type":           "string",
		"suffix":               nil,
		"field_length":         "full",
		"placeholder":          "Type a surname",
		"is_required":          false,
		"is_tooltip":           false,
		"tooltip_text":         nil,
		"metadata_id":          "a655f2a2-cd06-470e-8512-071a717d7e09",
		"position_in_metadata": 0,
	},
	{
		"id":                   "4310a3d3-749f-41dd-bdd6-388df30cf046",
		"field_name":           "Date of birth",
		"is_dynamic":           true,
		"field_type":           "date",
		"suffix":               nil,
		"field_length":         "half",
		"placeholder":          nil,
		"is_required":          false,
		"is_tooltip":           false,
		"tooltip_text":         nil,
		"metadata_id":          "a655f2a2-cd06-470e-8512-071a717d7e09",
		"position_in_metadata": 0,
	},
}
